### PR TITLE
Tabindex Fix + Focus on element after selection with keyboard

### PR DESCRIPTION
**Pull request by luaybs**
This maintains proper tabbing for the "remove" buttons and fixes a bug that was losing focus when selecting an item using the keyboard.

### CODE REVIEW

**Comment by luaybs** [comment]
@ryanb-gds Please take a look at this PR when you get the chance, thanks a lot!

**Comment by ryanb-gds** [comment]
Would you mind fixing the conflicts first? Thanks

**Comment by luaybs** [comment]
@ryanb-gds done!

**Comment by ChrisBAshton** [comment]
@luaybs apologies for the slow progress on our side - we don't often have outside contributors, and as you can probably tell, we aren't actively developing accessible-autocomplete-multiselect, but are in theory open to fixes!

Would you mind checking the linting error this PR is failing on, and also fixing up the commits (`git rebase -i main`) so that we have just the two relevant commits ("Add the tab index of the original select to the remove buttons" - ideally reworded to fit in one line - and "Rebuild dist"). Thank you 🙏

**Comment by luaybs** [comment]
@ChrisBAshton it's okay! I understand, and I appreciate the effort put into this project.

I updated the PR as requested, let me know if you need anything else.

**Comment by ChrisBAshton** [comment]
Hi @luaybs as of a couple of weeks ago (#76), accessible-autocomplete-multiselect is now deprecated and we expect to archive the repo as soon as we've removed its limited uses from GOV.UK. That being said, we won't be merging any further improvements at this stage.

Thanks for your time and apologies we didn't get around to merging your PR.

**Pull request closed without merging**
